backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Project" # Used in the UI, ie.: "New Post"
    folder: "site/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "text"}
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: Images
        name: images 
        widget: list
        field: {label: Image, name: image, widget: image}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Landing Page"
        name: "landing"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - label: Images
            name: images
            widget: list
            field: {label: Image, name: image, widget: image}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - {label: "Facebook", name: "facebook", widget: "text", required: false}
          - {label: "Twitter", name: "twitter", widget: "text", required: false}
          - {label: "Email", name: "email", widget: "text", required: false}
          - {label: "Ko-fi", name: "kofi", widget: "text", required: false}
          - {label: "Instagram", name: "Instagram", widget: "text", required: false}
      - file: "site/content/illustrations/_index.md"
        label: "Illustration Page"
        name: "illustrations"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - label: Illustrations
            name: illustrations
            widget: list
            fields: 
              - {label: "title", name: "title", widget: string} 
              - {label: Description, name: description, widget: string}
              - {label: Image, name: image, widget: image}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Image", name: "image", widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}          
      - file: "site/content/project/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Image", name: "image", widget: image, required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}  
          
